worker_processes auto;
user nginx;

events {
    worker_connections 1024;
    use epoll;

    multi_accept on;
    accept_mutex off;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://frontend-service:80;

            expires -1;
            add_header "Cache-Control" "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";

            access_log off;
            log_not_found off;
        }

        location ~* \.(css|js|woff|woff2)$ {
            proxy_pass http://frontend-service:80;

            expires 30d;
            add_header "Cache-Control" "public, no-transform";

            access_log off;
            log_not_found off;
        }
    }
}