name: CD-Test

services:
    frontend-service:
        build:
            context: ../..
            dockerfile: main/Dockerfile
        networks:
            - frontend-service-network
        deploy:
            restart_policy:
                condition: on-failure
      
    nginx-proxy:
        image: dockerhub.timeweb.cloud/library/nginx:alpine
        ports:
            - "80:80"
        networks:
            - frontend-service-network
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend-service
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 312M
                    cpus: '0.25'

networks:
    frontend-service-network:
        driver: bridge