name: CI-CD Test

on:
    push:
        branches-ignore: 
            - main
    
    pull_request:
        paths: 
            - 'main/**'
        
    workflow_dispatch:

jobs:
    ci-check:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./main

        steps:
            - name: Clone Repository Into Memory
              uses: actions/checkout@v4

            - name: Install NodeJS 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
                  cache-dependency-path: ./main/package-lock.json
                        
            - name: Install Dependences
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build Test
              run: npm run build