name: CI-CD Frontend

on:
    push:
        branches: ["main"]

    workflow_dispatch:

jobs:
    security:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./main

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm
                  cache-dependency-path: ./main/package-lock.json

            - name: Install Dependencies
              run: npm ci

            - name: Linter Secure
              run: npx oxlint

            - name: Build
              run: npm run build